// <auto-generated />
using System;
using System.Collections.Generic;
using KG.MES.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KG.MES.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OperationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("operation_time");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_type");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workplace_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("operation_logs");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("CommentIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("comment_ids");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsClaim")
                        .HasColumnType("boolean")
                        .HasColumnName("is_claim");

                    b.Property<bool>("IsEconom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_econom");

                    b.Property<bool>("IsOnlyPaid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_only_paid");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_number");

                    b.Property<decimal>("PlateArea")
                        .HasColumnType("numeric")
                        .HasColumnName("plate_area");

                    b.Property<int>("PlateCount")
                        .HasColumnType("integer")
                        .HasColumnName("plate_count");

                    b.Property<DateTime?>("ReadyDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WindowArea")
                        .HasColumnType("numeric")
                        .HasColumnName("window_area");

                    b.Property<int>("WindowCount")
                        .HasColumnType("integer")
                        .HasColumnName("window_count");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId");

                    b.HasIndex("OrderNumber");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("blocked_at");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workplace_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkplaceId");

                    b.ToTable("order_blocks");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderFootprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("production_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workplace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.HasIndex("ProductionOrderId", "WorkplaceId")
                        .IsUnique();

                    b.ToTable("order_footprints");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderSupply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("CommentIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("comment_ids");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("order_supply");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.PrimitiveCollection<List<Guid>>("CommentIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("comment_ids");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentWorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_workplace_id");

                    b.Property<string>("GlazingBead")
                        .HasColumnType("text")
                        .HasColumnName("glazing_bead");

                    b.Property<bool>("IsTwoSidePaint")
                        .HasColumnType("boolean")
                        .HasColumnName("is_two_side_paint");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Lumber")
                        .HasColumnType("text")
                        .HasColumnName("lumber");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWorkplaceId");

                    b.HasIndex("LegacyId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("production_orders");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condition_code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.ToTable("supply_conditions");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid?>("ConditionId")
                        .HasColumnType("uuid")
                        .HasColumnName("condition_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_date");

                    b.Property<Guid>("OrderSupplyId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_supply_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SupplyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("supply_type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique();

                    b.HasIndex("ConditionId");

                    b.HasIndex("OrderSupplyId");

                    b.HasIndex("SupplyTypeId");

                    b.HasIndex("OrderSupplyId", "SupplyTypeId")
                        .IsUnique();

                    b.ToTable("supply_items");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.ToTable("supply_types");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LegacyId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.UserWorkplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workplace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkplaceId");

                    b.HasIndex("UserId", "WorkplaceId")
                        .IsUnique();

                    b.ToTable("user_workplaces");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Workplace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsWorkplace")
                        .HasColumnType("boolean")
                        .HasColumnName("is_workplace");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("PreviousWorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_workplace_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LegacyId");

                    b.HasIndex("PreviousWorkplaceId");

                    b.ToTable("workplaces");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.WorkplaceTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromWorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_workplace_id");

                    b.Property<string>("LegacyId")
                        .HasColumnType("text")
                        .HasColumnName("legacy_id");

                    b.Property<Guid>("ToWorkplaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_workplace_id");

                    b.Property<string>("TransitionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transition_type");

                    b.HasKey("Id");

                    b.HasIndex("ToWorkplaceId");

                    b.HasIndex("FromWorkplaceId", "ToWorkplaceId")
                        .IsUnique();

                    b.ToTable("workplace_transitions");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Comment", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OperationLog", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("OperationLogs")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("OperationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("OperationLogs")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderBlock", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("OrderBlocks")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("OrderBlocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("OrderBlocks")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderFootprint", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("OrderFootprints")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("OrderFootprints")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderSupply", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Order", "Order")
                        .WithOne("OrderSupply")
                        .HasForeignKey("KG.MES.Shared.Models.Entities.OrderSupply", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.ProductionOrder", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "CurrentWorkplace")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("CurrentWorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KG.MES.Shared.Models.Entities.Order", "Order")
                        .WithOne("ProductionOrder")
                        .HasForeignKey("KG.MES.Shared.Models.Entities.ProductionOrder", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWorkplace");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyItem", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Comment", "CommentEntity")
                        .WithOne()
                        .HasForeignKey("KG.MES.Shared.Models.Entities.SupplyItem", "CommentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.SupplyCondition", "Condition")
                        .WithMany("SupplyItems")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KG.MES.Shared.Models.Entities.OrderSupply", "OrderSupply")
                        .WithMany("SupplyItems")
                        .HasForeignKey("OrderSupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.SupplyType", "SupplyType")
                        .WithMany("SupplyItems")
                        .HasForeignKey("SupplyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommentEntity");

                    b.Navigation("Condition");

                    b.Navigation("OrderSupply");

                    b.Navigation("SupplyType");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.User", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.UserWorkplace", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.User", "User")
                        .WithMany("UserWorkplaces")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "Workplace")
                        .WithMany("UserWorkplaces")
                        .HasForeignKey("WorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Workplace", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "PreviousWorkplace")
                        .WithMany()
                        .HasForeignKey("PreviousWorkplaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PreviousWorkplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.WorkplaceTransition", b =>
                {
                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "FromWorkplace")
                        .WithMany("FromTransitions")
                        .HasForeignKey("FromWorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KG.MES.Shared.Models.Entities.Workplace", "ToWorkplace")
                        .WithMany("ToTransitions")
                        .HasForeignKey("ToWorkplaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromWorkplace");

                    b.Navigation("ToWorkplace");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Order", b =>
                {
                    b.Navigation("OrderSupply");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.OrderSupply", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.ProductionOrder", b =>
                {
                    b.Navigation("OperationLogs");

                    b.Navigation("OrderBlocks");

                    b.Navigation("OrderFootprints");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyCondition", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.SupplyType", b =>
                {
                    b.Navigation("SupplyItems");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OperationLogs");

                    b.Navigation("OrderBlocks");

                    b.Navigation("UserWorkplaces");
                });

            modelBuilder.Entity("KG.MES.Shared.Models.Entities.Workplace", b =>
                {
                    b.Navigation("FromTransitions");

                    b.Navigation("OperationLogs");

                    b.Navigation("OrderBlocks");

                    b.Navigation("OrderFootprints");

                    b.Navigation("ProductionOrders");

                    b.Navigation("ToTransitions");

                    b.Navigation("UserWorkplaces");
                });
#pragma warning restore 612, 618
        }
    }
}
